CREATE TABLE TOKEN
(
  TOKEN_ID            INTEGER PRIMARY KEY,
  USER_ID             INTEGER,
  TOKEN_STRING        TEXT,
  CREATION_DATETIME   DATETIME DEFAULT CURRENT_TIMESTAMP,
  EXPIRATION_TIMESTAMP INTEGER,
  FOREIGN KEY (USER_ID) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE RISTORANTE
(
  P_IVA_RISTORANTE           TEXT PRIMARY KEY,
  NOME_RISTORANTE            TEXT NOT NULL,
  NUMERO_TELEFONO_RISTORANTE TEXT,
  IMG_URL_RISTORANTE         TEXT
);

CREATE TABLE CLIENTE
(
  ID_CLIENTE       INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME_CLIENTE     TEXT        NOT NULL,
  COGNOME_CLIENTE  TEXT        NOT NULL,
  EMAIL_CLIENTE    TEXT UNIQUE NOT NULL,
  PASSWORD_CLIENTE TEXT        NOT NULL,
  TELEFONO_CLIENTE TEXT NOT NULL,
  VIA_CLIENTE      TEXT        NOT NULL,
  CITTA_CLIENTE    TEXT        NOT NULL,
  CAP_CLIENTE      TEXT        NOT NULL,
  CITOFONO_CLIENTE TEXT        NOT NULL
);

CREATE TABLE MENU
(
  ID_PIATTO      INTEGER PRIMARY KEY AUTOINCREMENT,
  RISTORANTE_ID  INTEGER,
  NOME_PIATTO    TEXT           NOT NULL,
  DESCRIZIONE    TEXT,
  PREZZO         DECIMAL(10, 2) NOT NULL,
  IMG_URL_PIATTO TEXT,
  FOREIGN KEY (RISTORANTE_ID) REFERENCES RISTORANTE (P_IVA_RISTORANTE) ON DELETE CASCADE
);

CREATE TABLE SCONTRINO
(
  ID_SCONTRINO       INTEGER (16),
  ID_CLIENTE         INTEGER,
  DATA_ORA           DATETIME DEFAULT CURRENT_TIMESTAMP,
  TOTALE             DECIMAL(10, 2),
  ID_PIATTO          INTEGER,
  QUANTITA           INTEGER,
  PREZZO             DECIMAL(10, 2),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE,
  FOREIGN KEY (ID_PIATTO) REFERENCES MENU (ID_PIATTO) ON DELETE CASCADE
);
