-- Zona
CREATE TABLE ZONA
(
  ID_ZONA CHAR(4),
  CONSTRAINT PK_ZONA PRIMARY KEY (ID_ZONA)
);

-- Comune
CREATE TABLE COMUNE
(
  NOME_COMUNE    CHAR(20),
  PROVINCIA      CHAR(2),
  ZONA_ASSOCIATA CHAR(4),
  CONSTRAINT PK_COMUNE PRIMARY KEY (NOME_COMUNE),
  CONSTRAINT FK_COMUNE FOREIGN KEY (ZONA_ASSOCIATA) REFERENCES ZONA (ID_ZONA)
);

-- Locale
CREATE TABLE LOCALE
(
  P_IVA             CHAR(11),
  NOME_LOCALE       VARCHAR(20) UNIQUE NOT NULL,
  N_TELEFONO_LOCALE CHAR(10) UNIQUE    NOT NULL,
  VIA_LOCALE        VARCHAR(20)        NOT NULL,
  CAP_LOCALE        VARCHAR(20)        NOT NULL,
  COMUNE_SEDE       CHAR(20),
  CONSTRAINT PK_LOCALE PRIMARY KEY (P_IVA),
  CONSTRAINT FK_LOCALE FOREIGN KEY (COMUNE_SEDE) REFERENCES COMUNE (NOME_COMUNE)
);

-- Rider
CREATE TABLE RIDER
(
  CF_RIDER          CHAR(16),
  NOME_RIDER        VARCHAR(20) NOT NULL,
  COGNOME_RIDER     VARCHAR(20) NOT NULL,
  RIDER_ID          NUMBER(4,0) NOT NULL UNIQUE,
  TELEFONO_RIDER    CHAR(10) UNIQUE,
  COMUNE_LAVORATIVO CHAR(20),
  CONSTRAINT PK_RIDER PRIMARY KEY (CF_RIDER),
  CONSTRAINT FK_RIDER FOREIGN KEY (COMUNE_LAVORATIVO) REFERENCES COMUNE (NOME_COMUNE)
);

-- PRENOTAZIONE
CREATE TABLE PRENOTAZIONE
(
  ANNO              NUMBER(4,0) NOT NULL,
  DATA_PRENOTAZIONE DATE,
  GIORNO            VARCHAR(20) NOT NULL,
  ORA_INIZIO        TIMESTAMP   NOT NULL,
  ORA_FINE          TIMESTAMP   NOT NULL,
  CONSTRAINT PK_PRENOTAZIONE PRIMARY KEY (DATA_PRENOTAZIONE, ANNO, GIORNO),
  CONSTRAINT CK_ORARIO_PRENOTAZIONE CHECK (
      (EXTRACT(HOUR FROM ORA_INIZIO) >= 19 AND EXTRACT(HOUR FROM ORA_FINE) <= 24)
      AND
      (EXTRACT(HOUR FROM ORA_INIZIO) < EXTRACT(HOUR FROM ORA_FINE))),
  CONSTRAINT CHECK_GIORNO CHECK (GIORNO IN
                                 ('LUNEDI', 'MARTEDI', 'MERCOLEDI', 'GIOVEDI', 'VENERDI', 'SABATO', 'DOMENICA'))
);

-- Cliente
CREATE TABLE CLIENTE
(
  NOME_CLIENTE    VARCHAR(20) NOT NULL,
  COGNOME_CLIENTE VARCHAR(20),
  EMAIL           CHAR(30)    NOT NULL,
  COMUNE_RES      CHAR(20),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (EMAIL),
  CONSTRAINT FK_CLIENTE1 FOREIGN KEY (COMUNE_RES) REFERENCES COMUNE (NOME_COMUNE)
);

-- PAGAMENTO
CREATE TABLE PAGAMENTO
(
  SCONTRINO  CHAR(10),
  IMPORTO    NUMBER(2,0),
  METODO_PAY VARCHAR(30),
  CONSTRAINT PK_PAGAMENTO PRIMARY KEY (SCONTRINO),
  CONSTRAINT CHK_METODO CHECK (
        METODO_PAY = 'CONTANTI'
      OR METODO_PAY = 'CARTA DI CREDITO/DEBITO')
);

-- Informazioni consegna
CREATE TABLE INFORMAZIONI_CONSEGNA
(
  VIA_CLIENTE    CHAR(20) NOT NULL,
  CITTA_CLIENTE  CHAR(20) NOT NULL,
  CAP_CLIENTE    CHAR(10) NOT NULL,
  CITOFONO       VARCHAR(20),
  NOTE_PER_RIDER VARCHAR(30),
  EMAIL_CLIENTE  CHAR(30),
  CONSTRAINT PK_INFO PRIMARY KEY (VIA_CLIENTE, CITTA_CLIENTE, CAP_CLIENTE),
  CONSTRAINT FK_INFO FOREIGN KEY (EMAIL_CLIENTE) REFERENCES CLIENTE (EMAIL)
);

-- ORDINE
CREATE TABLE ORDINE
(
  N_ORDINE           NUMBER(3,0) NOT NULL,
  STATO              VARCHAR(20) NOT NULL,
  P_IVALOCALE        CHAR(11),
  CF_CONSEGNATORE    CHAR(16),
  EMAIL_DESTINATARIO CHAR(30),
  SCONTRINO_ORDINE   CHAR(10),
  DATA_E_ORA         TIMESTAMP,
  CONSTRAINT PK_ORDINE PRIMARY KEY (N_ORDINE),
  CONSTRAINT FK_ORDINE_LOCALE FOREIGN KEY (P_IVALOCALE) REFERENCES LOCALE (P_IVA),
  CONSTRAINT FK_ORDINE_RIDER FOREIGN KEY (CF_CONSEGNATORE) REFERENCES RIDER (CF_RIDER),
  CONSTRAINT FK_ORDINE_CLIENTE FOREIGN KEY (EMAIL_DESTINATARIO) REFERENCES CLIENTE (EMAIL),
  CONSTRAINT FK_ORDINE_SCONTRINO FOREIGN KEY (SCONTRINO_ORDINE) REFERENCES PAGAMENTO (SCONTRINO),
  CONSTRAINT CHK_STATO CHECK (
    STATO IN ('IN LAVORAZIONE', 'RITIRATO', 'IN CONSEGNA', 'CONSEGNATO'))
);

-- Prodotto
CREATE TABLE PRODOTTO
(
  ID_PRODOTTO   NUMBER      NOT NULL,
  NOME_PRODOTTO VARCHAR(20) NOT NULL,
  TIPO_PRODOTTO VARCHAR(20),
  P_IVA_LOCALE  CHAR(11),
  CONSTRAINT PK_PRODOTTO PRIMARY KEY (ID_PRODOTTO),
  CONSTRAINT FK_PRDOTTO FOREIGN KEY (P_IVA_LOCALE) REFERENCES LOCALE (P_IVA)
);

-- Presenti
CREATE TABLE PRESENTI
(
  IDPRODOTTO NUMBER,
  NORDINE    NUMBER,
  QUANTITÀ   NUMBER(2,0),
  CONSTRAINT PK_PRESENTI PRIMARY KEY (IDPRODOTTO, NORDINE),
  CONSTRAINT FK_PRESENTI1 FOREIGN KEY (IDPRODOTTO) REFERENCES PRODOTTO (ID_PRODOTTO),
  CONSTRAINT FK_PRESENTI2 FOREIGN KEY (NORDINE) REFERENCES ORDINE (N_ORDINE)
);

-- Effettuano
CREATE TABLE EFFETTUANO
(
  CODF_RIDER        CHAR(16),
  ANNO1             NUMBER(4,0),
  DATAPRENOTAZIONE  DATE,
  GIORNO_LAVORATIVO VARCHAR(20),
  CONSTRAINT PK_EFFETTUANO PRIMARY KEY (CODF_RIDER, ANNO1, DATAPRENOTAZIONE, GIORNO_LAVORATIVO),
  CONSTRAINT FK_EFFETTUANO1 FOREIGN KEY (CODF_RIDER) REFERENCES RIDER (CF_RIDER),
  CONSTRAINT FK_EFFETTUANO2 FOREIGN KEY (ANNO1, DATAPRENOTAZIONE, GIORNO_LAVORATIVO) REFERENCES PRENOTAZIONE (ANNO, DATA_PRENOTAZIONE, GIORNO)
);
