-- Admin
CREATE USER 'RESPONSABILE_ADMIN'@'localhost' IDENTIFIED BY 'ADMIN';
GRANT ALL PRIVILEGES ON *.* TO 'RESPONSABILE_ADMIN'@'localhost';
FLUSH PRIVILEGES;

-- Rider
CREATE USER 'RIDER_USER'@'localhost' IDENTIFIED BY 'PASSWORD_RIDER';
GRANT SELECT ON `delivery vesuviano`.INFORMAZIONI_CONSEGNA TO 'RIDER_USER'@'localhost';
GRANT SELECT ON `delivery vesuviano`.LOCALE TO 'RIDER_USER'@'localhost';
GRANT SELECT ON `delivery vesuviano`.ORDINE TO 'RIDER_USER'@'localhost';
GRANT SELECT ON `delivery vesuviano`.PAGAMENTO TO 'RIDER_USER'@'localhost';
GRANT INSERT, UPDATE ON `delivery vesuviano`.EFFETTUANO TO 'RIDER_USER'@'localhost';
FLUSH PRIVILEGES;

-- Cliente
CREATE USER 'CLIENTE_USER'@'localhost' IDENTIFIED BY 'PASSWORD_CLIENTE';
GRANT SELECT ON `delivery vesuviano`.LOCALE TO 'CLIENTE_USER'@'localhost';
GRANT SELECT, INSERT, UPDATE ON `delivery vesuviano`.INFORMAZIONI_CONSEGNA TO 'CLIENTE_USER'@'localhost';
GRANT SELECT ON `delivery vesuviano`.PAGAMENTO TO 'CLIENTE_USER'@'localhost';
GRANT SELECT ON `delivery vesuviano`.PRODOTTO TO 'CLIENTE_USER'@'localhost';
GRANT SELECT ON `delivery vesuviano`.CLIENTE_VIEW TO 'CLIENTE_USER'@'localhost';
FLUSH PRIVILEGES;