CREATE OR REPLACE PROCEDURE NUMERO_CONSEGNE_RIDER(CF_RIDER IN CHAR)
  IS
  CONT INTEGER;
BEGIN
  SELECT COUNT(*)
  INTO CONT
  FROM ORDINE
  WHERE CF_CONSEGNATORE = CF_RIDER;
  DBMS_OUTPUT.PUT_LINE('IL RIDER CON CF ' || CF_RIDER || ' HA EFFETTUATO ' || CONT || '    CONSEGNE.');
END;

CREATE OR REPLACE PROCEDURE NUMERO_ORDINI_PER_COMUNE
  IS
BEGIN
  FOR REC IN (SELECT COMUNE.NOME_COMUNE, COUNT(*) AS NUM_ORDINI
              FROM COMUNE
                     INNER JOIN CLIENTE ON COMUNE.NOME_COMUNE = CLIENTE.COMUNE_RES
                     INNER JOIN ORDINE ON CLIENTE.EMAIL = ORDINE.EMAIL_DESTINATARIO
              GROUP BY COMUNE.NOME_COMUNE)
    LOOP
      DBMS_OUTPUT.PUT_LINE('COMUNE: ' || REC.NOME_COMUNE || ', NUMERO ORDINI: ' || REC.NUM_ORDINI);
    END LOOP;
END;

CREATE OR REPLACE PROCEDURE CALCOLAGUADAGNI
  IS
BEGIN
  FOR REC IN (SELECT SUM(IMPORTO) AS TOTALE_PAGAMENTI
              FROM PAGAMENTO
                     INNER JOIN ORDINE ON ORDINE.SCONTRINO_ORDINE = PAGAMENTO.SCONTRINO
              GROUP BY ORDINE.SCONTRINO_ORDINE)
    LOOP
      DBMS_OUTPUT.PUT_LINE('TOTALE PAGAMENTI: ' || REC.TOTALE_PAGAMENTI);
    END LOOP;
END;

CREATE OR REPLACE PROCEDURE RIDER_PRENOTATI
  IS
BEGIN
  FOR REC IN (
    SELECT EFFETTUANO.CODF_RIDER, COUNT(*) AS NUM_PRENOTAZIONI
    FROM EFFETTUANO
           INNER JOIN RIDER ON EFFETTUANO.CODF_RIDER = RIDER.CF_RIDER
    GROUP BY EFFETTUANO.CODF_RIDER
    )
    LOOP
      DBMS_OUTPUT.PUT_LINE('RIDER:' || REC.CODF_RIDER || ', NUMERO DI PRENOTAZIONI: ' || REC.NUM_PRENOTAZIONI);
    END LOOP;
END;
