CREATE VIEW PRENOTAZIONERIDER AS
SELECT RIDER.CF_RIDER, PRENOTAZIONE.DATA_PRENOTAZIONE
FROM RIDER
       INNER JOIN EFFETTUANO ON RIDER.CF_RIDER = EFFETTUANO.CODF_RIDER
       INNER JOIN PRENOTAZIONE ON EFFETTUANO.DATAPRENOTAZIONE = PRENOTAZIONE.DATA_PRENOTAZIONE;

CREATE VIEW CLIENTE_VIEW AS
SELECT LOCALE.NOME_LOCALE, ORDINE.N_ORDINE, ORDINE.STATO, PAGAMENTO.IMPORTO
FROM LOCALE
       INNER JOIN ORDINE ON LOCALE.P_IVA = ORDINE.P_IVALOCALE
       INNER JOIN PAGAMENTO ON ORDINE.SCONTRINO_ORDINE = PAGAMENTO.SCONTRINO;

DROP VIEW PRENOTAZIONERIDER;
DROP VIEW CLIENTE_VIEW;
