create PROCEDURE CALCOLAGUADAGNI
  IS
BEGIN
  FOR REC IN (SELECT SUM(IMPORTO) AS TOTALE_PAGAMENTI
              FROM PAGAMENTO
                     INNER JOIN ORDINE ON ORDINE.SCONTRINO_ORDINE = PAGAMENTO.SCONTRINO
              GROUP BY ORDINE.SCONTRINO_ORDINE)
    LOOP
      DBMS_OUTPUT.PUT_LINE('TOTALE PAGAMENTI: ' || REC.TOTALE_PAGAMENTI);
    END LOOP;
END;
/

