create PROCEDURE NUMERO_ORDINI_PER_COMUNE
  IS
BEGIN
  FOR REC IN (SELECT COMUNE.NOME_COMUNE, COUNT(*) AS NUM_ORDINI
              FROM COMUNE
                     INNER JOIN CLIENTE ON COMUNE.NOME_COMUNE = CLIENTE.COMUNE_RES
                     INNER JOIN ORDINE ON CLIENTE.EMAIL = ORDINE.EMAIL_DESTINATARIO
              GROUP BY COMUNE.NOME_COMUNE)
    LOOP
      DBMS_OUTPUT.PUT_LINE('COMUNE: ' || REC.NOME_COMUNE || ', NUMERO ORDINI: ' || REC.NUM_ORDINI);
    END LOOP;
END;
/

